cmd DockObserver
cmd SurfaceFlinger
cmd SurfaceFlingerAIDL
cmd accessibility
cmd account
cmd activity
cmd activity_task
cmd adb
cmd adservices_manager
cmd alarm
cmd ambient_context
cmd android.frameworks.cameraservice.service.ICameraService/default
cmd android.frameworks.location.altitude.IAltitudeService/default
cmd android.frameworks.sensorservice.ISensorManager/default
cmd android.frameworks.stats.IStats/default
cmd android.hardware.gnss.IGnss/default
cmd android.hardware.light.ILights/default
cmd android.hardware.memtrack.IMemtrack/default
cmd android.hardware.neuralnetworks.IDevice/mtk-gpu_shim
cmd android.hardware.neuralnetworks.IDevice/mtk-neuron_shim
cmd android.hardware.power.IPower/default
cmd android.hardware.security.keymint.IKeyMintDevice/default
cmd android.hardware.security.keymint.IRemotelyProvisionedComponent/default
cmd android.hardware.security.secureclock.ISecureClock/default
cmd android.hardware.security.sharedsecret.ISharedSecret/default
cmd android.hardware.vibrator.IVibrator/default
cmd android.hardware.vibrator.IVibratorManager/default
cmd android.os.UpdateEngineService
cmd android.os.UpdateEngineStableService
cmd android.security.apc
cmd android.security.authorization
cmd android.security.compat
cmd android.security.identity
cmd android.security.legacykeystore
cmd android.security.maintenance
cmd android.security.metrics
cmd android.system.keystore2.IKeystoreService/default
cmd android.system.net.netd.INetd/default
cmd android.system.suspend.ISystemSuspend/default
cmd anrmanager
cmd app_binding
cmd app_hibernation
cmd app_integrity
cmd app_search
cmd appops
cmd appwidget
cmd attention
cmd attestation_verification
cmd audio
cmd auth
cmd autofill
cmd avatarpipe
cmd background_install_control
cmd backup
cmd battery
cmd batteryproperties
cmd batterystats
cmd binder_calls_stats
cmd biometric
cmd blob_store
cmd bluetooth_manager
cmd bugreport
cmd cacheinfo
cmd carrier_config
cmd clipboard
cmd color_display
cmd companiondevice
cmd connectivity
cmd connectivity_native
cmd connmetrics
cmd content
cmd content_capture
cmd country_detector
cmd cpuinfo
cmd crossprofileapps
cmd dataloader_manager
cmd dbinfo
cmd device_config
cmd device_identifiers
cmd device_lock
cmd device_policy
cmd device_state
cmd deviceidle
cmd devicestoragemonitor
cmd diskstats
cmd display
cmd domain_verification
cmd dreams
cmd drm.drmManager
cmd dropbox
cmd dynamic_system
cmd emergency_affordance
cmd ethernet
cmd external_vibrator_service
cmd face
cmd file_integrity
cmd fingerprint
cmd font
cmd game
cmd gfxinfo
cmd gpu
cmd grammatical_inflection
cmd graphicsstats
cmd gwsd
cmd hardware_properties
cmd healthconnect
cmd hiber
cmd imms
cmd imtksms
cmd incidentcompanion
cmd incremental
cmd input
cmd input_method
cmd inputflinger
cmd ions
cmd iphonesubinfo
cmd iphonesubinfoEx
cmd ipsec
cmd isms
cmd isub
cmd jobscheduler
cmd kolun
cmd launcherapps
cmd legacy_permission
cmd lights
cmd locale
cmd location
cmd lock_settings
cmd logcat
cmd looper_stats
cmd manager
cmd mdns
cmd media.VTS
cmd media.aaudio
cmd media.audio_flinger
cmd media.audio_policy
cmd media.camera
cmd media.camera.proxy
cmd media.extractor
cmd media.metrics
cmd media.player
cmd media.resource_manager
cmd media.resource_observer
cmd media_communication
cmd media_metrics
cmd media_projection
cmd media_resource_monitor
cmd media_router
cmd media_session
cmd meminfo
cmd memtrack.proxy
cmd midi
cmd mount
cmd mtkIms
cmd mtksimphonebook
cmd mwis
cmd nearby
cmd netd_listener
cmd netpolicy
cmd netstats
cmd network_management
cmd network_score
cmd network_stack
cmd network_time_update_service
cmd network_watchlist
cmd nfc
cmd nfc.st_ext
cmd nfc_settings
cmd notification
cmd oem_lock
cmd oem_unlock_data
cmd ondevicepersonalization_system_service
cmd os_app_ops
cmd os_audio_change
cmd otadexopt
cmd overlay
cmd pac_proxy
cmd package
cmd package_native
cmd particular_feature
cmd people
cmd performance_hint
cmd permission
cmd permission_checker
cmd permissionmgr
cmd persistent_data_block
cmd phone
cmd phoneEx
cmd pinner
cmd platform_compat
cmd platform_compat_native
cmd power
cmd power_hal_mgr_service
cmd powerstats
cmd print
cmd processinfo
cmd procstats
cmd reboot_readiness
cmd recovery
cmd remote_provisioning
cmd resources
cmd restrictions
cmd role
cmd rollback
cmd runtime
cmd safety_center
cmd sand_accessor
cmd scheduling_policy
cmd sdk_sandbox
cmd search
cmd search_engine_service
cmd search_ui
cmd sec_key_att_app_id_provider
cmd secure_element
cmd securitycom_access
cmd selection_toolbar
cmd sensor_privacy
cmd sensorservice
cmd serial
cmd servicediscovery
cmd settings
cmd shortcut
cmd simphonebook
cmd slice
cmd smartspace
cmd soundtrigger
cmd soundtrigger_middleware
cmd speech_recognition
cmd stats
cmd statsbootstrap
cmd statscompanion
cmd statsmanager
cmd statusbar
cmd storaged
cmd storaged_pri
cmd storagestats
cmd system_config
cmd system_server_dumper
cmd system_update
cmd tare
cmd telecom
cmd telephony.mtkregistry
cmd telephony.registry
cmd telephony_ims
cmd testharness
cmd tethering
cmd textclassification
cmd textservices
cmd texttospeech
cmd thermalservice
cmd time_detector
cmd time_zone_detector
cmd tracing.proxy
cmd tran_aipl
cmd tran_bootstrap_service_manager
cmd tran_pwhub
cmd tran_service_manager
cmd tran_wifi
cmd tranphone
cmd transparency
cmd trust
cmd uimode
cmd updatelock
cmd uri_grants
cmd usagestats
cmd usb
cmd user
cmd vcn_management
cmd vendor.mediatek.framework.mtksf_ext.IMtkSF_ext/default
cmd vendor.transsion.hardware.tranfacaidl.ITranfacAidl/default
cmd vendor.transsion.hardware.trannet.ITranNet/default
cmd vibrator_manager
cmd virtualdevice
cmd voiceinteraction
cmd vpn_management
cmd wallpaper
cmd wallpaper_effects_generation
cmd wearable_sensing
cmd webviewupdate
cmd wifi
cmd wifinl80211
cmd wifip2p
cmd wifiscanner
cmd window
